version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /FCS.wdl
    testParameterFiles:
      - /inputs.json
    authors:
      - name: "Hailey Loucks"
        email: "hloucks@ucsc.edu"
